### ISSUE TITLE
added rstudio add-in

### ISSUE THREAD

**Issue by jwijffels** [kevinushey/cronR#1]
FYI. Forked this to https://github.com/jwijffels/cronR and added an RStudio add-in

**Comment by MarkEdmondson1234** [comment]
Hi, this is a nice addition but it doesn't work on RStudio Server as the download button looks for local files, rather than the ones on the server. I guess you can download the file then reupload again but perhaps you know of a more direct way.

**Comment by jwijffels** [comment]
I know, I'm working on this at this very moment. Should be fixed hopefully by today somewhere using the shinyFiles package.

**Comment by MarkEdmondson1234** [comment]
Great, in that case may I make two other requests - I hope to use this for novice user's scheduling their own scripts on RStudio server so its to make it as easy as possible for them:
1. A pop up rather than in the View window, as on my laptop its a little difficult to view and see everything
2. Default the Rscript path to be the current working directory - at the moment it looks to be within the cronR package itself.

**Comment by jwijffels** [comment]
Agree on the popup
I'll see what I can do on the Rscript path. Not 100% sure on this however. I would prefer that this is set only once. That's why the path is stored inside an RDS file inside the package. But maybe I can create something like if it wasn't set already in that RDS file, use the current working directory.

**Comment by jwijffels** [comment]
FYI. Changes are put on https://github.com/bnosac/cronR
Feel free to give comments.

**Comment by MarkEdmondson1234** [comment]
Had a chance to look at this today, its tip top 👍

**Comment by jwijffels** [comment]
Feel free to share your view on a blog somewhere.

**Comment by jeborsel** [comment]
I am using cronR with Rstudio server inside a docker container on Azure cloud and Rstudio addin doesn't work because Rscript command needs full path for the command itself.

So line 200 in cron_rstudioaddin.R
`cmd <- sprintf("Rscript %s %s >> %s.log 2>&1", myscript, rscript_args, tools::file_path_sans_ext(myscript))`

doesn't work, but this does work for me:

`cmd <- sprintf("/usr/local/bin/Rscript %s %s >> %s.log 2>&1", myscript, rscript_args, tools::file_path_sans_ext(myscript))`

**Comment by jwijffels** [comment]
Yes, if Rscript is not in your path, this will not work. I've updated the script to let it use R_HOME/bin/Rscript

**Comment by kevinushey** [comment]
@jwijffels: Do you mind if I link to your fork from this repository (e.g. from the `README`)? I think it's fair that yours gets exposure since I don't have plans to maintain this version, so it's best if people are linked directly to yours.

**Comment by jwijffels** [comment]
OK, no problem. If you link to https://github.com/bnosac/cronR, i'll maintain the package.
